name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release/ds3os-loader
        # The desired behavior if no files are found using the provided path.
        ignore: Do not output any warnings or errors, the action does not fail
        if-no-files-found: warn

        retention-days: 90
